/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f9f9ff",
        "surface-dim": "#cfdaf2",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "surface-container": "#e7eeff",
        "surface-container-high": "#dee8ff",
        "surface-container-highest": "#d8e3fb",
        "on-surface": "#111c2d",
        "on-surface-variant": "#424750",
        "inverse-surface": "#263143",
        "inverse-on-surface": "#ecf1ff",
        "outline": "#727782",
        "outline-variant": "#c2c6d2",
        "surface-tint": "#2060a3",
        "primary": "#004b89",
        "on-primary": "#ffffff",
        "primary-container": "#2563a6",
        "on-primary-container": "#ccdfff",
        "inverse-primary": "#a4c9ff",
        "secondary": "#7d5700",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffc65e",
        "on-secondary-container": "#755100",
        "tertiary": "#005535",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#007047",
        "on-tertiary-container": "#95f0bd",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d4e3ff",
        "primary-fixed-dim": "#a4c9ff",
        "on-primary-fixed": "#001c39",
        "on-primary-fixed-variant": "#004883",
        "secondary-fixed": "#ffdeaa",
        "secondary-fixed-dim": "#f5bd57",
        "on-secondary-fixed": "#271900",
        "on-secondary-fixed-variant": "#5f4100",
        "tertiary-fixed": "#9af5c2",
        "tertiary-fixed-dim": "#7ed9a7",
        "on-tertiary-fixed": "#002112",
        "on-tertiary-fixed-variant": "#005233",
        "background": "#f9f9ff",
        "on-background": "#111c2d",
        "surface-variant": "#d8e3fb",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "full": "9999px",
      },
      spacing: {
        "gutter-mobile": "0.75rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "gutter": "1rem",
        "margin-mobile": "1rem",
        "margin": "1.5rem",
      },
      fontFamily: {
        "display-title": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-md-medium": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-xs-mono": ["JetBrains Mono", "monospace"],
        "caption": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
