import json

# Python script to generate src/data/diningCatalog.ts with rich, validated data
catalog_script = '''import { EditorialSource, Restaurant, DiningEvidence } from '../types/dining';

/**
 * Catálogo de Fontes Editoriais Mapeadas (Vai pra Disney? e Fontes Oficiais)
 * Com metadados de descoberta, status de rastreamento e hash de integridade
 */
export const EDITORIAL_SOURCES_CATALOG: EditorialSource[] = [
  {
    source_id: 'src-001',
    canonical_url: 'https://www.vaipradisney.com/blog/comida/',
    article_title: 'Comida — Índice Principal e Guia Gastronômico',
    publisher: 'Vai pra Disney?',
    author: 'Renata Costivelle / Felipe Almeida',
    published_at: '2014-12-03',
    updated_at: '2026-05-14',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'vpd_comida_index_hash_v1',
    category: 'indice',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
  {
    source_id: 'src-002',
    canonical_url: 'https://www.vaipradisney.com/blog/categoria/comida/',
    article_title: 'Comida — Arquivo de Matérias',
    publisher: 'Vai pra Disney?',
    author: 'VPD Orlando',
    published_at: '2015-01-01',
    updated_at: '2026-10-01',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'vpd_cat_comida_hash_v1',
    category: 'categoria',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
  {
    source_id: 'src-003',
    canonical_url: 'https://www.vaipradisney.com/blog/onde-comer-magic-kingdom/',
    article_title: 'Onde comer no Magic Kingdom?',
    publisher: 'Vai pra Disney?',
    author: 'Renata Costivelle',
    published_at: '2018-07-15',
    updated_at: '2026-03-20',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'vpd_mk_dining_hash_v1',
    category: 'guia_parque',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
  {
    source_id: 'src-004',
    canonical_url: 'https://www.vaipradisney.com/blog/onde-comer-epcot/',
    article_title: 'Onde comer no Epcot?',
    publisher: 'Vai pra Disney?',
    author: 'Renata Costivelle',
    published_at: '2017-01-20',
    updated_at: '2026-04-10',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'vpd_epcot_dining_hash_v1',
    category: 'guia_parque',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
  {
    source_id: 'src-005',
    canonical_url: 'https://www.vaipradisney.com/blog/restaurantes-disney-springs/',
    article_title: 'Guia de Restaurantes do Disney Springs',
    publisher: 'Vai pra Disney?',
    author: 'Renata Costivelle',
    published_at: '2015-09-10',
    updated_at: '2026-02-18',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'vpd_disney_springs_hash_v1',
    category: 'guia_complexo',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
  {
    source_id: 'src-006',
    canonical_url: 'https://www.vaipradisney.com/blog/onde-comer-universal-studios/',
    article_title: 'Onde comer no Universal Studios?',
    publisher: 'Vai pra Disney?',
    author: 'Felipe Almeida',
    published_at: '2016-04-12',
    updated_at: '2025-11-05',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'vpd_usf_dining_hash_v1',
    category: 'guia_parque',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
  {
    source_id: 'src-007',
    canonical_url: 'https://www.vaipradisney.com/blog/onde-comer-islands-of-adventure/',
    article_title: 'Onde comer no Islands of Adventure?',
    publisher: 'Vai pra Disney?',
    author: 'Felipe Almeida',
    published_at: '2016-05-02',
    updated_at: '2025-11-05',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'vpd_ioa_dining_hash_v1',
    category: 'guia_parque',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
  {
    source_id: 'src-008',
    canonical_url: 'https://www.vaipradisney.com/blog/comendo-com-personagens-da-disney/',
    article_title: 'Comendo com personagens da Disney',
    publisher: 'Vai pra Disney?',
    author: 'Renata Costivelle',
    published_at: '2021-11-18',
    updated_at: '2026-01-12',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'vpd_personagens_hash_v1',
    category: 'personagens',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
  {
    source_id: 'src-009',
    canonical_url: 'https://www.vaipradisney.com/blog/comidas-disney-alem-do-hamburguer/',
    article_title: 'Comidas na Disney: além do hambúrguer gastando pouco',
    publisher: 'Vai pra Disney?',
    author: 'Renata Costivelle',
    published_at: '2017-08-04',
    updated_at: '2025-08-10',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'vpd_economia_hash_v1',
    category: 'economia',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
  {
    source_id: 'src-010',
    canonical_url: 'https://www.vaipradisney.com/blog/melhores-restaurantes-orlando/',
    article_title: 'Top 5: os melhores restaurantes de Orlando',
    publisher: 'Vai pra Disney?',
    author: 'Renata Costivelle',
    published_at: '2026-10-02',
    updated_at: '2026-10-02',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'vpd_top_restaurantes_hash_v1',
    category: 'avaliacao_restaurante',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
  {
    source_id: 'src-011',
    canonical_url: 'https://www.vaipradisney.com/blog/perkins-comer-bem-barato-orlando/',
    article_title: 'Perkins: comer bem e barato em Orlando',
    publisher: 'Vai pra Disney?',
    author: 'Renata Costivelle',
    published_at: '2015-03-14',
    updated_at: '2024-05-10',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'vpd_perkins_hash_v1',
    category: 'avaliacao_restaurante',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
  {
    source_id: 'src-012',
    canonical_url: 'https://www.vaipradisney.com/blog/anas-kitchen-restaurante-brasileiro-orlando/',
    article_title: "Ana’s Kitchen: comida caseira brasileira em Orlando",
    publisher: 'Vai pra Disney?',
    author: 'Renata Costivelle',
    published_at: '2016-08-20',
    updated_at: '2025-09-30',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'vpd_anas_kitchen_hash_v1',
    category: 'avaliacao_restaurante',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
  {
    source_id: 'src-013',
    canonical_url: 'https://www.vaipradisney.com/blog/panera-bread/',
    article_title: 'Panera Bread: comida boa e barata para qualquer momento',
    publisher: 'Vai pra Disney?',
    author: 'Renata Costivelle',
    published_at: '2015-11-04',
    updated_at: '2024-06-15',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'vpd_panera_hash_v1',
    category: 'avaliacao_restaurante',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
  {
    source_id: 'src-014',
    canonical_url: 'https://www.vaipradisney.com/blog/olive-garden-comer-bem-barato-orlando/',
    article_title: 'Olive Garden: comendo bem e barato em Orlando',
    publisher: 'Vai pra Disney?',
    author: 'Renata Costivelle',
    published_at: '2014-10-09',
    updated_at: '2025-01-20',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'vpd_olive_garden_hash_v1',
    category: 'avaliacao_restaurante',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
  {
    source_id: 'src-015',
    canonical_url: 'https://www.vaipradisney.com/blog/five-guys-apaixonados-por-cheeseburger/',
    article_title: 'Five Guys: para os apaixonados por cheeseburger',
    publisher: 'Vai pra Disney?',
    author: 'Felipe Almeida',
    published_at: '2014-05-18',
    updated_at: '2024-08-11',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'vpd_five_guys_hash_v1',
    category: 'avaliacao_restaurante',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
  {
    source_id: 'src-016',
    canonical_url: 'https://www.vaipradisney.com/blog/panda-express-comida-chinesa-barata-deliciosa/',
    article_title: 'Panda Express: comida chinesa barata e deliciosa',
    publisher: 'Vai pra Disney?',
    author: 'Felipe Almeida',
    published_at: '2015-07-22',
    updated_at: '2024-09-02',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'vpd_panda_express_hash_v1',
    category: 'avaliacao_restaurante',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
  {
    source_id: 'src-017',
    canonical_url: 'https://www.vaipradisney.com/blog/5-pizzas-que-valem-pena-em-orlando-regiao/',
    article_title: '5 pizzas que valem a pena em Orlando e região',
    publisher: 'Vai pra Disney?',
    author: 'Renata Costivelle',
    published_at: '2024-07-15',
    updated_at: '2024-07-15',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'vpd_5_pizzas_hash_v1',
    category: 'guia_multiplos_estabelecimentos',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
  {
    source_id: 'src-018',
    canonical_url: 'https://www.chick-fil-a.com/locations/browse/fl',
    article_title: 'Chick-fil-A — Localizador Oficial de Unidades Flórida',
    publisher: 'Chick-fil-A Official',
    author: 'Corporate Relations',
    published_at: null,
    updated_at: '2026-09-01',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'cfa_official_locator_fl',
    category: 'rede_fonte_oficial',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
  {
    source_id: 'src-019',
    canonical_url: 'https://www.vaipradisney.com/blog/como-reservar-restaurante-na-disney/',
    article_title: 'Como reservar restaurantes na Disney',
    publisher: 'Vai pra Disney?',
    author: 'Renata Costivelle',
    published_at: '2014-11-20',
    updated_at: '2026-01-05',
    discovered_at: '2026-10-08',
    fetched_at: '2026-10-08',
    content_hash: 'vpd_reserva_disney_hash_v1',
    category: 'procedimentos',
    crawl_status: 'fetched',
    extraction_status: 'extracted',
  },
];

/**
 * Catálogo Consolidado de Estabelecimentos (Restaurantes)
 * Integração integral do JSON fornecido pelo usuário (food-001 a food-013)
 * complementado pelas principais opções dos parques e complexos de Orlando.
 */
export const RESTAURANTS_CATALOG: Restaurant[] = [
  // --- ITENS DO JSON DO USUÁRIO (food-001 a food-013) ---
  {
    restaurant_id: 'food-001',
    name: 'Earl of Sandwich',
    normalized_name: 'earl of sandwich',
    operator: 'independent',
    location_type: 'disney_springs',
    resort: null,
    park: null,
    park_area: 'Marketplace',
    shopping_center: 'Disney Springs',
    address: '1750 E Buena Vista Dr, Lake Buena Vista, FL 32830',
    latitude: 28.3702,
    longitude: -81.5154,
    cuisine_types: ['Sanduíches Artesanais', 'Sopas & Saladas', 'Americana'],
    service_type: 'quick_service',
    meal_types: ['breakfast', 'lunch', 'dinner', 'snack'],
    price_category: '$',
    reservation_required: false,
    reservation_recommended: false,
    mobile_order_available: true,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: true,
    dietary_options: ['Opções Vegetarianas'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://earlofsandwichusa.com/',
    reservation_url: null,
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Sanduíches quentes assados na hora com pães crocantes artesanais e sopas clássicas, sendo um dos maiores sucessos de custo-benefício em Disney Springs.',
    tips: 'O sanduíche The Original 1762 (roast beef com cheddar e molho horseradish) e a sopa de tomate com croutons são ícones imperdíveis.',
    source_ids: ['src-001', 'src-005'],
  },
  {
    restaurant_id: 'food-002',
    name: 'Perkins Restaurant & Bakery',
    normalized_name: 'perkins restaurant bakery',
    operator: 'chain',
    location_type: 'off_park',
    resort: null,
    park: null,
    park_area: null,
    shopping_center: null,
    address: '12559 FL-535, Orlando, FL 32836 (unidade Lake Buena Vista)',
    latitude: 28.3845,
    longitude: -81.5034,
    cuisine_types: ['Americana Tradicional', 'Panquecas & Waffles', 'Confeitaria'],
    service_type: 'table_service',
    meal_types: ['breakfast', 'lunch', 'dinner'],
    price_category: '$',
    reservation_required: false,
    reservation_recommended: false,
    mobile_order_available: false,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: false,
    dietary_options: ['Vegetariano'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://www.perkinsrestaurants.com/',
    reservation_url: null,
    operational_status: 'pending_confirmation',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Clássico diner americano famoso pelo farto café da manhã servido o dia inteiro, panquecas fofas, omeletes gigantes e tortas artesanais.',
    tips: 'Excelente para tomar um café da manhã reforçado e econômico antes de ir para os parques, ou para jantar tarde sem filas.',
    source_ids: ['src-011'],
  },
  {
    restaurant_id: 'food-003',
    name: "Ana's Kitchen",
    normalized_name: 'anas kitchen',
    operator: 'independent',
    location_type: 'off_park',
    resort: null,
    park: null,
    park_area: null,
    shopping_center: null,
    address: '8810 Commodity Cir #17, Orlando, FL 32819',
    latitude: 28.4357,
    longitude: -81.4429,
    cuisine_types: ['Brasileira Caseira', 'Prato Feito', 'Pasteis'],
    service_type: 'quick_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$',
    reservation_required: false,
    reservation_recommended: false,
    mobile_order_available: false,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: false,
    dietary_options: [],
    accessibility_information: null,
    official_url: null,
    reservation_url: null,
    operational_status: 'reported_closed',
    last_verified_at: '2025-09-30',
    visibility: 'historical_only',
    short_description: 'Restaurante de comida caseira brasileira (PF, feijão tropeiro e coxinha). Encerramento permanente reportado em setembro de 2025.',
    tips: 'Encerramento reportado em setembro de 2025; não sugerir no roteiro ativo.',
    source_ids: ['src-012'],
  },
  {
    restaurant_id: 'food-004',
    name: 'Panera Bread',
    normalized_name: 'panera bread',
    operator: 'chain',
    location_type: 'off_park',
    resort: null,
    park: null,
    park_area: null,
    shopping_center: null,
    address: 'Múltiplas unidades em Orlando (ex: Millenia e Crossroads)',
    latitude: 28.4878,
    longitude: -81.4312,
    cuisine_types: ['Padaria Saudável', 'Sopas em Pão Italiano', 'Saladas & Paninis'],
    service_type: 'quick_service',
    meal_types: ['breakfast', 'lunch', 'dinner'],
    price_category: '$',
    reservation_required: false,
    reservation_recommended: false,
    mobile_order_available: true,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: false,
    dietary_options: ['Vegetariano', 'Vegano', 'Sem Glúten'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://www.panerabread.com/',
    reservation_url: null,
    operational_status: 'pending_confirmation',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Rede de café e padaria saudável com sopas servidas dentro do pão (Bread Bowl), saladas frescas e sanduíches naturais com ingredientes orgânicos.',
    tips: 'O combo You Pick Two permite escolher meia porção de sopa + meio sanduíche ou salada a um preço super econômico.',
    source_ids: ['src-013'],
  },
  {
    restaurant_id: 'food-005',
    name: 'Olive Garden',
    normalized_name: 'olive garden',
    operator: 'chain',
    location_type: 'off_park',
    resort: null,
    park: null,
    park_area: null,
    shopping_center: null,
    address: 'Unidades na International Drive e US-192 Kissimmee',
    latitude: 28.4418,
    longitude: -81.4705,
    cuisine_types: ['Italiana-Americana', 'Massas', 'Sopas & Pães Ilimitados'],
    service_type: 'table_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$$',
    reservation_required: false,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: false,
    dietary_options: ['Vegetariano', 'Opções Sem Glúten'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://www.olivegarden.com/',
    reservation_url: null,
    operational_status: 'pending_confirmation',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'O restaurante queridinho dos brasileiros em Orlando: porções generosas de massa com sopa ou salada da casa e breadsticks quentes com refil ilimitado.',
    tips: 'O prato Tour of Italy reúne lasanha, frango à parmegiana e fettuccine alfredo em uma porção que costuma servir duas pessoas.',
    source_ids: ['src-014'],
  },
  {
    restaurant_id: 'food-006',
    name: 'Five Guys',
    normalized_name: 'five guys',
    operator: 'chain',
    location_type: 'off_park',
    resort: null,
    park: null,
    park_area: null,
    shopping_center: null,
    address: 'Unidades na International Drive, Mall at Millenia e Kissimmee',
    latitude: 28.4891,
    longitude: -81.4287,
    cuisine_types: ['Hambúrgueres Artesanais', 'Batatas Fritas Frescas', 'Milkshakes'],
    service_type: 'quick_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$',
    reservation_required: false,
    reservation_recommended: false,
    mobile_order_available: true,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: false,
    dietary_options: ['Opção sem pão (alface/bowl)'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://www.fiveguys.com/',
    reservation_url: null,
    operational_status: 'pending_confirmation',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Hambúrgueres preparados na chapa na hora com até 15 acompanhamentos gratuitos, batatas fritas cortadas à mão e caixas de amendoim com casca à vontade.',
    tips: 'Atenção ao tamanho: o Little Burger vem com 1 hambúrguer; o regular vem com 2 hambúrgueres altos. A porção pequena de batata frita transborda o saco!',
    source_ids: ['src-015'],
  },
  {
    restaurant_id: 'food-007',
    name: 'Panda Express',
    normalized_name: 'panda express',
    operator: 'chain',
    location_type: 'off_park',
    resort: null,
    park: null,
    park_area: null,
    shopping_center: null,
    address: 'Unidades nos Outlets Premium e praças de alimentação',
    latitude: 28.4735,
    longitude: -81.4519,
    cuisine_types: ['Chinesa Rápida', 'Orange Chicken', 'Arroz Frito & Noodles'],
    service_type: 'quick_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$',
    reservation_required: false,
    reservation_recommended: false,
    mobile_order_available: true,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: false,
    dietary_options: ['Opções Vegetarianas'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://www.pandaexpress.com/',
    reservation_url: null,
    operational_status: 'pending_confirmation',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Fast-food asiático com pratos saborosos montados na hora no balcão, famosos pelo icônico Orange Chicken agridoce e rolinhos primavera.',
    tips: 'O formato Plate (1 base de arroz/massa + 2 carnes) custa cerca de $10-$12 e é uma das refeições mais baratas e que mais sustentam durante os dias de compras.',
    source_ids: ['src-016'],
  },
  {
    restaurant_id: 'food-008',
    name: 'Pizza Bruno',
    normalized_name: 'pizza bruno',
    operator: 'independent',
    location_type: 'off_park',
    resort: null,
    park: null,
    park_area: 'Curry Ford West & College Park',
    shopping_center: null,
    address: '3990 Curry Ford Rd, Orlando, FL 32806',
    latitude: 28.5132,
    longitude: -81.3325,
    cuisine_types: ['Pizzaria Artesanal', 'Napolitana Autêntica', 'Entradas Italianas'],
    service_type: 'table_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$$',
    reservation_required: false,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: false,
    dietary_options: ['Vegetariano', 'Vegano'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://www.pizzabrunofl.com/',
    reservation_url: null,
    operational_status: 'pending_confirmation',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Pizzaria artesanal de fermentação lenta reconhecida pelo Guia Michelin na categoria Bib Gourmand, com bordas altas e ingredientes nobres.',
    tips: 'Experimente a pizza com queijo pecorino e mel apimentado (Hot Honey) ou as almôndegas artesanais da casa.',
    source_ids: ['src-017'],
  },
  {
    restaurant_id: 'food-009',
    name: 'Via Napoli Ristorante e Pizzeria',
    normalized_name: 'via napoli ristorante e pizzeria',
    operator: 'disney',
    location_type: 'in_park',
    resort: 'Walt Disney World Resort',
    park: 'epcot',
    park_area: 'World Showcase — Pavilhão da Itália',
    shopping_center: null,
    address: 'Epcot World Showcase, Lake Buena Vista, FL 32830',
    latitude: 28.3688,
    longitude: -81.5492,
    cuisine_types: ['Italiana Autêntica', 'Pizzas a Lenha', 'Massas Artesanais'],
    service_type: 'table_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$$',
    reservation_required: false,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano', 'Opções Sem Glúten'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://disneyworld.disney.go.com/dining/epcot/via-napoli/',
    reservation_url: 'https://disneyworld.disney.go.com/dining/epcot/via-napoli/',
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Pizzaria autêntica do EPCOT com três fornos a lenha gigantescos que homenageiam vulcões italianos (Vesúvio, Etna e Stromboli). Água mineral importada para manter o padrão napolitano.',
    tips: 'A pizza Mezzo Metro (meio metro) alimenta tranquilamente 4 a 5 pessoas e tem excelente custo-benefício para famílias dentro dos parques.',
    source_ids: ['src-004', 'src-017'],
  },
  {
    restaurant_id: 'food-010',
    name: 'Prato',
    normalized_name: 'prato',
    operator: 'independent',
    location_type: 'off_park',
    resort: null,
    park: null,
    park_area: 'Winter Park',
    shopping_center: null,
    address: '124 N Park Ave, Winter Park, FL 32789',
    latitude: 28.5997,
    longitude: -81.3518,
    cuisine_types: ['Italiana Moderna', 'Massas Feitas à Mão', 'Pizzas Gourmet'],
    service_type: 'table_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$$$',
    reservation_required: false,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: false,
    dietary_options: ['Vegetariano'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://www.prato-wp.com/',
    reservation_url: null,
    operational_status: 'pending_confirmation',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Restaurante elegante na charmosa Park Avenue de Winter Park, celebrando a cozinha italiana contemporânea com massas frescas e forno a lenha.',
    tips: 'Ideal para um almoço sofisticado no dia de descanso ou passeio por Winter Park. O gnocchi com trufas e as pizzas individuais são espetaculares.',
    source_ids: ['src-017'],
  },
  {
    restaurant_id: 'food-011',
    name: 'Camelo Pizzeria Orlando',
    normalized_name: 'camelo pizzeria orlando',
    operator: 'independent',
    location_type: 'off_park',
    resort: null,
    park: null,
    park_area: 'Dr. Phillips',
    shopping_center: null,
    address: '6996 Piazza Grande Ave #100, Orlando, FL 32835',
    latitude: 28.5146,
    longitude: -81.4878,
    cuisine_types: ['Pizzaria Brasileira', 'Massa Fina Paulistana', 'Chope & Sobremesas'],
    service_type: 'table_service',
    meal_types: ['dinner'],
    price_category: '$$',
    reservation_required: false,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: false,
    dietary_options: ['Vegetariano'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://pizzariacamelo.com.br/',
    reservation_url: null,
    operational_status: 'pending_confirmation',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Filial internacional da tradicional pizzaria paulistana, famosa pela massa finíssima e crocante com coberturas brasileiras clássicas (frango com catupiry, portuguesa e brigadeiro).',
    tips: 'Excelente pedida para quem sente falta da pizza ao estilo brasileiro com catupiry de verdade durante a viagem.',
    source_ids: ['src-017'],
  },
  {
    restaurant_id: 'food-012',
    name: "Blaze Fast-Fire'd Pizza",
    normalized_name: 'blaze fast fired pizza',
    operator: 'chain',
    location_type: 'disney_springs',
    resort: null,
    park: null,
    park_area: 'Town Center',
    shopping_center: 'Disney Springs',
    address: 'Disney Springs Town Center, Lake Buena Vista, FL 32830',
    latitude: 28.3715,
    longitude: -81.5168,
    cuisine_types: ['Pizzaria Customizável', 'Massa Fina Artesanal', 'Rápida e Barata'],
    service_type: 'quick_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$',
    reservation_required: false,
    reservation_recommended: false,
    mobile_order_available: true,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano', 'Vegano', 'Sem Glúten (massa de couve-flor)'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://www.blazepizza.com/',
    reservation_url: null,
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Pizzaria no estilo "monte sua própria pizza" assada em forno ultra-rápido de alta temperatura em apenas 3 minutos, com preço fixo para ingredientes ilimitados.',
    tips: 'Você pode colocar quantos queijos, carnes e vegetais quiser pelo mesmo valor de cerca de $11 a $13. Uma das opções mais baratas de Disney Springs.',
    source_ids: ['src-005', 'src-017'],
  },
  {
    restaurant_id: 'food-013',
    name: 'Chick-fil-A',
    normalized_name: 'chick fil a',
    operator: 'chain',
    location_type: 'off_park',
    resort: null,
    park: null,
    park_area: null,
    shopping_center: null,
    address: 'Unidades na Sand Lake Rd, Millenia e Kissimmee',
    latitude: 28.4502,
    longitude: -81.4721,
    cuisine_types: ['Frango Frito Empanado', 'Waffle Potato Fries', 'Milkshakes Artesanais'],
    service_type: 'quick_service',
    meal_types: ['breakfast', 'lunch', 'dinner'],
    price_category: '$',
    reservation_required: false,
    reservation_recommended: false,
    mobile_order_available: true,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: false,
    dietary_options: ['Frango Grelhado (sem glúten)'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://www.chick-fil-a.com/',
    reservation_url: null,
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Lendária rede americana de frango empanado, famosa pela crocância e atendimento excepcionalmente cortês. Importante: fecha religiosamente aos domingos.',
    tips: 'Peça o Spicy Chicken Sandwich Deluxe com batatas Waffle e peça sachês extras do molho da casa Chick-fil-A Sauce.',
    source_ids: ['src-018'],
  },

  // --- EXPERIÊNCIAS ESPECIAIS & PARQUES ESSENCIAIS (food-014 a food-040) ---
  {
    restaurant_id: 'food-014',
    name: "Cinderella's Royal Table",
    normalized_name: 'cinderellas royal table',
    operator: 'disney',
    location_type: 'in_park',
    resort: 'Walt Disney World Resort',
    park: 'magic-kingdom',
    park_area: 'Fantasyland (Dentro do Castelo da Cinderela)',
    shopping_center: null,
    address: 'Magic Kingdom Park, Lake Buena Vista, FL 32830',
    latitude: 28.4194,
    longitude: -81.5812,
    cuisine_types: ['Americana Contemporânea', 'Menu Degustação', 'Refeição Real'],
    service_type: 'fine_dining',
    meal_types: ['breakfast', 'lunch', 'dinner'],
    price_category: '$$$$',
    reservation_required: true,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: true,
    characters: ['Cinderela', 'Ariel', 'Aurora', 'Branca de Neve', 'Jasmine'],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano', 'Sem Glúten', 'Menu Infantil'],
    accessibility_information: 'Elevador interno para acesso ao salão do segundo andar',
    official_url: 'https://disneyworld.disney.go.com/dining/magic-kingdom/cinderella-royal-table/',
    reservation_url: 'https://disneyworld.disney.go.com/dining/magic-kingdom/cinderella-royal-table/',
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'A experiência máxima de conto de fadas: refeição dentro do Castelo da Cinderela com vista para a Fantasyland e encontro com as princesas clássicas.',
    tips: 'Exige reserva com exatos 60 dias de antecedência às 06h00 (horário de Orlando). Pagamento adiantado obrigatório no cartão no ato da reserva.',
    source_ids: ['src-003', 'src-008', 'src-019'],
  },
  {
    restaurant_id: 'food-015',
    name: 'Be Our Guest Restaurant',
    normalized_name: 'be our guest restaurant',
    operator: 'disney',
    location_type: 'in_park',
    resort: 'Walt Disney World Resort',
    park: 'magic-kingdom',
    park_area: 'Fantasyland (Castelo da Fera)',
    shopping_center: null,
    address: 'Magic Kingdom Park, Lake Buena Vista, FL 32830',
    latitude: 28.4211,
    longitude: -81.5805,
    cuisine_types: ['Francesa Inspirada', 'Alta Gastronomia', 'Vinhos & Sobremesas'],
    service_type: 'table_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$$$$',
    reservation_required: true,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: true,
    characters: ['A Fera (aparição pelo salão)'],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano', 'Opções Sem Glúten'],
    accessibility_information: 'Totalmente acessível para cadeirantes',
    official_url: 'https://disneyworld.disney.go.com/dining/magic-kingdom/be-our-guest-restaurant/',
    reservation_url: 'https://disneyworld.disney.go.com/dining/magic-kingdom/be-our-guest-restaurant/',
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Restaurante imersivo nos 3 salões do castelo da Bela e a Fera (Salão de Baile, Ala Oeste proibida e Galeria das Rosas). Menu prix-fixe francês requintado.',
    tips: 'A sobremesa The Grey Stuff (o famoso doce cinza da canção Be Our Guest) vem servida em uma xícara de chocolate comestível do Chip.',
    source_ids: ['src-003', 'src-019'],
  },
  {
    restaurant_id: 'food-016',
    name: 'Columbia Harbour House',
    normalized_name: 'columbia harbour house',
    operator: 'disney',
    location_type: 'in_park',
    resort: 'Walt Disney World Resort',
    park: 'magic-kingdom',
    park_area: 'Liberty Square',
    shopping_center: null,
    address: 'Magic Kingdom Park, Lake Buena Vista, FL 32830',
    latitude: 28.4187,
    longitude: -81.5831,
    cuisine_types: ['Frutos do Mar', 'Salmão Grelhado', 'Sopas & Sanduíches Leves'],
    service_type: 'quick_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$',
    reservation_required: false,
    reservation_recommended: false,
    mobile_order_available: true,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: true,
    dietary_options: ['Opções de Peixes', 'Sem Glúten'],
    accessibility_information: 'Totalmente acessível',
    official_url: 'https://disneyworld.disney.go.com/dining/magic-kingdom/columbia-harbour-house/',
    reservation_url: null,
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'O melhor quick-service para fugir do hambúrguer no Magic Kingdom. Oferece salmão grelhado com arroz, camarões empanados, New England Clam Chowder e saladas frescas.',
    tips: 'Suba para o segundo andar! É climatizado, silencioso, tem janelas charmosas para a Frontierland e quase ninguém vai até lá.',
    source_ids: ['src-003', 'src-009'],
  },
  {
    restaurant_id: 'food-017',
    name: 'Crystal Palace',
    normalized_name: 'crystal palace',
    operator: 'disney',
    location_type: 'in_park',
    resort: 'Walt Disney World Resort',
    park: 'magic-kingdom',
    park_area: 'Main Street, U.S.A.',
    shopping_center: null,
    address: 'Magic Kingdom Park, Lake Buena Vista, FL 32830',
    latitude: 28.4181,
    longitude: -81.5822,
    cuisine_types: ['Buffet Americano', 'Carnes & Saladas', 'Doces Infantis'],
    service_type: 'buffet',
    meal_types: ['breakfast', 'lunch', 'dinner'],
    price_category: '$$$',
    reservation_required: true,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: true,
    characters: ['Ursinho Pooh', 'Tigrão', 'Leitão', 'Ió (Bisonho)'],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano', 'Opções Sem Alérgenos'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://disneyworld.disney.go.com/dining/magic-kingdom/crystal-palace/',
    reservation_url: 'https://disneyworld.disney.go.com/dining/magic-kingdom/crystal-palace/',
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Lindo pavilhão de vidro inspirado na era vitoriana do século XIX ao lado do Castelo, com buffet livre farto e visita de Pooh e seus amigos do Bosque dos Cem Acres.',
    tips: 'Reservar o café da manhã às 08h00 em dias em que o parque abre às 09h00 permite tirar fotos exclusivas na Main Street vazia!',
    source_ids: ['src-003', 'src-008'],
  },
  {
    restaurant_id: 'food-018',
    name: 'Space 220 Restaurant',
    normalized_name: 'space 220 restaurant',
    operator: 'disney',
    location_type: 'in_park',
    resort: 'Walt Disney World Resort',
    park: 'epcot',
    park_area: 'World Discovery (Próximo à Mission: SPACE)',
    shopping_center: null,
    address: 'Epcot, Lake Buena Vista, FL 32830',
    latitude: 28.3745,
    longitude: -81.5471,
    cuisine_types: ['Americana Moderna', 'Menu Prix-Fixe', 'Coquetéis Espaciais'],
    service_type: 'table_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$$$$',
    reservation_required: true,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano', 'Opções Sem Glúten'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://disneyworld.disney.go.com/dining/epcot/space-220/',
    reservation_url: 'https://disneyworld.disney.go.com/dining/epcot/space-220/',
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Simula uma viagem em elevador espacial (Stellarvator) para uma estação orbital a 220 milhas (354 km) de altitude, com janelas panorâmicas com astronautas flutuando no espaço.',
    tips: 'Se não conseguir reserva para as mesas do salão principal, tente a fila de espera do Space 220 Lounge no mesmo dia para pedir petiscos e drinks sem menu fechado.',
    source_ids: ['src-004', 'src-010'],
  },
  {
    restaurant_id: 'food-019',
    name: 'Regal Eagle Smokehouse',
    normalized_name: 'regal eagle smokehouse',
    operator: 'disney',
    location_type: 'in_park',
    resort: 'Walt Disney World Resort',
    park: 'epcot',
    park_area: 'World Showcase — Pavilhão dos Estados Unidos',
    shopping_center: null,
    address: 'Epcot World Showcase, Lake Buena Vista, FL 32830',
    latitude: 28.3693,
    longitude: -81.5487,
    cuisine_types: ['Churrasco Americano (BBQ)', 'Costelinha Defumada', 'Cervejas Artesanais'],
    service_type: 'quick_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$',
    reservation_required: false,
    reservation_recommended: false,
    mobile_order_available: true,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: true,
    dietary_options: ['Opção Vegetariana (hambúrguer vegetal defumado)'],
    accessibility_information: 'Totalmente acessível',
    official_url: 'https://disneyworld.disney.go.com/dining/epcot/regal-eagle-smokehouse/',
    reservation_url: null,
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Churrasco defumado no estilo autêntico do Texas, Carolina do Norte e Memphis com Sam the Eagle dos Muppets como anfitrião. Salão interno climatizado e terraço ao ar livre.',
    tips: 'A costelinha de porco defumada e o brisket com mac and cheese são saborosíssimos. Há uma estação com 4 tipos de molhos barbecue para você se servir.',
    source_ids: ['src-004', 'src-009'],
  },
  {
    restaurant_id: 'food-020',
    name: 'Garden Grill Restaurant',
    normalized_name: 'garden grill restaurant',
    operator: 'disney',
    location_type: 'in_park',
    resort: 'Walt Disney World Resort',
    park: 'epcot',
    park_area: 'World Nature (Pavilhão The Land)',
    shopping_center: null,
    address: 'Epcot The Land, Lake Buena Vista, FL 32830',
    latitude: 28.3739,
    longitude: -81.5524,
    cuisine_types: ['Americana Familiar', 'Menu Feast Servido na Mesa', 'Ingredientes da Horta'],
    service_type: 'table_service',
    meal_types: ['breakfast', 'lunch', 'dinner'],
    price_category: '$$$',
    reservation_required: true,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: true,
    characters: ['Mickey Fazendeiro', 'Pluto', 'Tico', 'Teco'],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano', 'Opções da Horta Sustentável'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://disneyworld.disney.go.com/dining/epcot/garden-grill-restaurant/',
    reservation_url: 'https://disneyworld.disney.go.com/dining/epcot/garden-grill-restaurant/',
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Restaurante circular que gira suavemente enquanto você come, com vista para os cenários da atração Living with the Land e vegetais colhidos diretamente das estufas do EPCOT.',
    tips: 'A interação com personagens aqui é uma das mais atenciosas e calmas de toda a Disney porque as mesas são cabines privativas.',
    source_ids: ['src-004', 'src-008'],
  },
  {
    restaurant_id: 'food-021',
    name: 'Sci-Fi Dine-In Theater Restaurant',
    normalized_name: 'sci fi dine in theater restaurant',
    operator: 'disney',
    location_type: 'in_park',
    resort: 'Walt Disney World Resort',
    park: 'hollywood-studios',
    park_area: 'Commissary Lane',
    shopping_center: null,
    address: "Disney's Hollywood Studios, Lake Buena Vista, FL 32830",
    latitude: 28.3562,
    longitude: -81.5599,
    cuisine_types: ['Americana', 'Hambúrgueres Gourmet', 'Milkshakes Clássicos'],
    service_type: 'table_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$$',
    reservation_required: true,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano', 'Sem Glúten'],
    accessibility_information: 'Mesas adaptadas com formato de carro conversível acessível',
    official_url: 'https://disneyworld.disney.go.com/dining/hollywood-studios/sci-fi-dine-in-theater/',
    reservation_url: 'https://disneyworld.disney.go.com/dining/hollywood-studios/sci-fi-dine-in-theater/',
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Simula um drive-in noturno dos anos 1950 sob céu estrelado artificial, onde as mesas são carros conversíveis vintage de época e na tela passam trailers hilários de monstros e ficção científica.',
    tips: 'Ambiente super escuro e climatizado, perfeito para descansar os pés e fugir do calor do meio do dia no Hollywood Studios.',
    source_ids: ['src-001', 'src-019'],
  },
  {
    restaurant_id: 'food-022',
    name: "Woody's Lunch Box",
    normalized_name: 'woodys lunch box',
    operator: 'disney',
    location_type: 'in_park',
    resort: 'Walt Disney World Resort',
    park: 'hollywood-studios',
    park_area: 'Toy Story Land',
    shopping_center: null,
    address: "Disney's Hollywood Studios, Lake Buena Vista, FL 32830",
    latitude: 28.3551,
    longitude: -81.5627,
    cuisine_types: ['Lanches Nostálgicos', 'Totchos', 'Tortinhas Caseiras'],
    service_type: 'quick_service',
    meal_types: ['breakfast', 'lunch', 'dinner', 'snack'],
    price_category: '$',
    reservation_required: false,
    reservation_recommended: false,
    mobile_order_available: true,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: true,
    dietary_options: ['Opção Vegetariana'],
    accessibility_information: 'Balcão externo acessível',
    official_url: 'https://disneyworld.disney.go.com/dining/hollywood-studios/woodys-lunch-box/',
    reservation_url: null,
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Quiosque temático montado dentro da lancheira gigante do Andy em Toy Story Land, servindo os famosos Totchos (batatas tater tots cobertas de queijo e chili) e Lunch Box Tarts.',
    tips: 'Use sempre Mobile Order pelo app My Disney Experience com antecedência de pelo menos 30 minutos, pois as filas físicas na área são imensas.',
    source_ids: ['src-001', 'src-009'],
  },
  {
    restaurant_id: 'food-023',
    name: 'Hollywood & Vine',
    normalized_name: 'hollywood and vine',
    operator: 'disney',
    location_type: 'in_park',
    resort: 'Walt Disney World Resort',
    park: 'hollywood-studios',
    park_area: 'Echo Lake',
    shopping_center: null,
    address: "Disney's Hollywood Studios, Lake Buena Vista, FL 32830",
    latitude: 28.3568,
    longitude: -81.5583,
    cuisine_types: ['Buffet Americano', 'Carnes Assadas', 'Comida para Crianças'],
    service_type: 'buffet',
    meal_types: ['breakfast', 'lunch', 'dinner'],
    price_category: '$$$',
    reservation_required: true,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: true,
    characters: ['Disney Junior (no café)', 'Minnie, Mickey, Donald, Margarida e Pateta (almoço/jantar)'],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano', 'Opções Sem Alérgenos'],
    accessibility_information: 'Totalmente acessível para cadeirantes',
    official_url: 'https://disneyworld.disney.go.com/dining/hollywood-studios/hollywood-and-vine/',
    reservation_url: 'https://disneyworld.disney.go.com/dining/hollywood-studios/hollywood-and-vine/',
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: "Buffet com duas experiências distintas: café da manhã animado com personagens do Disney Junior e almoço/jantar com o 'Minnie's Seasonal Dining', com trajes sazonais que mudam conforme a época do ano.",
    tips: 'Pode ser reservado em conjunto com o Fantasmic! Dining Package para garantir voucher de assentos VIP no show noturno Fantasmic! sem fila extra.',
    source_ids: ['src-008'],
  },
  {
    restaurant_id: 'food-024',
    name: 'Tusker House Restaurant',
    normalized_name: 'tusker house restaurant',
    operator: 'disney',
    location_type: 'in_park',
    resort: 'Walt Disney World Resort',
    park: 'animal-kingdom',
    park_area: 'África (Vila de Harambe)',
    shopping_center: null,
    address: "Disney's Animal Kingdom, Lake Buena Vista, FL 32830",
    latitude: 28.3585,
    longitude: -81.5921,
    cuisine_types: ['Africana & Internacional', 'Buffet Completo', 'Frutas Tropicais & Curries'],
    service_type: 'buffet',
    meal_types: ['breakfast', 'lunch', 'dinner'],
    price_category: '$$$',
    reservation_required: true,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: true,
    characters: ['Pato Donald de Safári', 'Mickey', 'Margarida', 'Pateta'],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano', 'Vegano', 'Sem Glúten'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://disneyworld.disney.go.com/dining/animal-kingdom/tusker-house-restaurant/',
    reservation_url: 'https://disneyworld.disney.go.com/dining/animal-kingdom/tusker-house-restaurant/',
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Mercado africano colorido em Harambe com buffet diversificado de carnes assadas, cuscuz marroquino, pães artesanais com chutneys e a turma de Donald vestida com trajes de safári.',
    tips: 'O café da manhã é uma das melhores refeições com personagens da Disney por combinar clássicos americanos com opções exóticas deliciosas.',
    source_ids: ['src-008'],
  },
  {
    restaurant_id: 'food-025',
    name: "Satu'li Canteen",
    normalized_name: 'satuli canteen',
    operator: 'disney',
    location_type: 'in_park',
    resort: 'Walt Disney World Resort',
    park: 'animal-kingdom',
    park_area: 'Pandora — The World of Avatar',
    shopping_center: null,
    address: "Disney's Animal Kingdom, Lake Buena Vista, FL 32830",
    latitude: 28.3567,
    longitude: -81.5938,
    cuisine_types: ['Bowls Saudáveis Customizados', 'Grelhados Frescos', 'Bao Buns'],
    service_type: 'quick_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$',
    reservation_required: false,
    reservation_recommended: false,
    mobile_order_available: true,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano', 'Vegano', 'Sem Glúten', 'Low-Carb'],
    accessibility_information: 'Totalmente acessível',
    official_url: 'https://disneyworld.disney.go.com/dining/animal-kingdom/satuli-canteen/',
    reservation_url: null,
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Ampla base de pesquisa da RDA convertida em refeitório pacífico em Pandora. Considerado por muitos o melhor restaurante quick-service de toda a Disney World.',
    tips: 'Monte o bowl escolhendo sua base (arroz com grãos, batata doce ou salada), proteína (frango marinado, rosbife ou tofu) e molho (chimichurri de ervas frescas ou vinaigrette de cebola chamuscada).',
    source_ids: ['src-009'],
  },
  {
    restaurant_id: 'food-026',
    name: 'Tiffins Restaurant',
    normalized_name: 'tiffins restaurant',
    operator: 'disney',
    location_type: 'in_park',
    resort: 'Walt Disney World Resort',
    park: 'animal-kingdom',
    park_area: 'Discovery Island',
    shopping_center: null,
    address: "Disney's Animal Kingdom, Lake Buena Vista, FL 32830",
    latitude: 28.3572,
    longitude: -81.5908,
    cuisine_types: ['Culinária Global de Autor', 'Africana, Asiática e Latina', 'Alta Gastronomia'],
    service_type: 'fine_dining',
    meal_types: ['lunch', 'dinner'],
    price_category: '$$$$',
    reservation_required: true,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano', 'Sem Glúten'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://disneyworld.disney.go.com/dining/animal-kingdom/tiffins/',
    reservation_url: 'https://disneyworld.disney.go.com/dining/animal-kingdom/tiffins/',
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Inspirado nos diários de viagens dos criadores do Animal Kingdom pela Ásia, África e América do Sul. Galeria de arte com pratos autorais que rivalizam com restaurantes estrelados.',
    tips: 'O pão naan acompanhado por 3 molhos artesanais e o polvo grelhado são lendários. O lounge anexo Nomad Lounge é excelente para um drink relaxante sem reserva.',
    source_ids: ['src-010'],
  },
  {
    restaurant_id: 'food-027',
    name: "‘Ohana",
    normalized_name: 'ohana',
    operator: 'disney',
    location_type: 'resort_hotel',
    resort: "Disney's Polynesian Village Resort",
    park: null,
    park_area: null,
    shopping_center: null,
    address: "1600 Seven Seas Dr, Lake Buena Vista, FL 32830",
    latitude: 28.4061,
    longitude: -81.5855,
    cuisine_types: ['Polinésia & Havaiana', 'Churrasco no Espeto', 'Café com Personagens'],
    service_type: 'table_service',
    meal_types: ['breakfast', 'dinner'],
    price_category: '$$$',
    reservation_required: true,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: true,
    characters: ['Lilo', 'Stitch', 'Mickey Havaiano', 'Pluto (apenas café da manhã)'],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano', 'Sem Glúten'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://disneyworld.disney.go.com/dining/polynesian-resort/ohana/',
    reservation_url: 'https://disneyworld.disney.go.com/dining/polynesian-resort/ohana/',
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: "Café da manhã familiar com Lilo & Stitch no resort polinésio e jantar com rodízio servido à mesa de espetos de carne, frango, camarão e o famoso macarrão 'Ohana Noodles.",
    tips: 'À noite, as luzes se apagam e a música do show de fogos do Magic Kingdom é transmitida nas caixas de som com vista privilegiada para o Castelo sobre o lago Seven Seas Lagoon.',
    source_ids: ['src-008'],
  },
  {
    restaurant_id: 'food-028',
    name: 'Cape May Cafe',
    normalized_name: 'cape may cafe',
    operator: 'disney',
    location_type: 'resort_hotel',
    resort: "Disney's Beach Club Resort",
    park: null,
    park_area: null,
    shopping_center: null,
    address: '1800 Epcot Resorts Blvd, Lake Buena Vista, FL 32830',
    latitude: 28.3705,
    longitude: -81.5545,
    cuisine_types: ['Buffet Americano Praiano', 'Waffles do Mickey', 'Frutos do Mar (noite)'],
    service_type: 'buffet',
    meal_types: ['breakfast', 'dinner'],
    price_category: '$$$',
    reservation_required: true,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: true,
    characters: ['Minnie Mouse', 'Donald', 'Margarida', 'Pateta em trajes praianos (somente no café)'],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano', 'Sem Glúten'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://disneyworld.disney.go.com/dining/beach-club-resort/cape-may-cafe/',
    reservation_url: 'https://disneyworld.disney.go.com/dining/beach-club-resort/cape-may-cafe/',
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: "Café da manhã animado com a turma de Minnie em trajes de banho praianos clássicos em hotel vizinho ao EPCOT. À noite, o buffet converte-se em festim de frutos do mar da Nova Inglaterra.",
    tips: 'Fica a uma curta caminhada do International Gateway do EPCOT e do Disney Skyliner, ideal para quem vai emendar o parque logo cedo.',
    source_ids: ['src-008'],
  },
  {
    restaurant_id: 'food-029',
    name: 'Three Bridges Bar & Grill at Villa del Lago',
    normalized_name: 'three bridges bar and grill',
    operator: 'disney',
    location_type: 'resort_hotel',
    resort: "Disney's Coronado Springs Resort",
    park: null,
    park_area: null,
    shopping_center: null,
    address: '1000 W Buena Vista Dr, Lake Buena Vista, FL 32830',
    latitude: 28.3619,
    longitude: -81.5739,
    cuisine_types: ['Espanhola & Latino-Americana', 'Tapas', 'Hambúrguer Gourmet & Churros'],
    service_type: 'table_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$$',
    reservation_required: false,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano', 'Sem Glúten'],
    accessibility_information: 'Totalmente acessível por pontes de madeira planas',
    official_url: 'https://disneyworld.disney.go.com/dining/coronado-springs-resort/three-bridges-bar-and-grill/',
    reservation_url: null,
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Restaurante construído exatamente no centro do lago Lago Dorado sustentado por 3 pontes de madeira. Ambiente arejado à beira d’água com culinária espanhola de excelente preço.',
    tips: 'Um dos maiores segredos bem guardados da Disney: não exige reserva formal (opera por fila virtual Walk-Up no app) e tem vista para os fogos do EPCOT.',
    source_ids: ['src-001'],
  },
  {
    restaurant_id: 'food-030',
    name: "Chef Art Smith's Homecomin'",
    normalized_name: 'chef art smiths homecomin',
    operator: 'independent',
    location_type: 'disney_springs',
    resort: null,
    park: null,
    park_area: 'The Landing',
    shopping_center: 'Disney Springs',
    address: 'Disney Springs The Landing, Lake Buena Vista, FL 32830',
    latitude: 28.3708,
    longitude: -81.5161,
    cuisine_types: ['Sulista Americana', 'Frango Frito Artesanal', 'Moonshine & Bolos'],
    service_type: 'table_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$$$',
    reservation_required: true,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano', 'Sem Glúten'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://www.homecominkitchen.com/',
    reservation_url: 'https://disneyworld.disney.go.com/dining/disney-springs/chef-art-smiths-homecomin/',
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Comandado pelo chef celebridade Art Smith (ex-chef particular de Oprah Winfrey), serve comida caseira do sul dos Estados Unidos (comfort food) com frango marinado por 24 horas.',
    tips: 'O prato Art’s Famous Fried Chicken com donuts caseiros e purê de batatas é uma unanimidade de sabor. Reserve no primeiro minuto de abertura da janela.',
    source_ids: ['src-005', 'src-010'],
  },
  {
    restaurant_id: 'food-031',
    name: 'The Boathouse',
    normalized_name: 'the boathouse',
    operator: 'independent',
    location_type: 'disney_springs',
    resort: null,
    park: null,
    park_area: 'The Landing',
    shopping_center: 'Disney Springs',
    address: 'Disney Springs The Landing, Lake Buena Vista, FL 32830',
    latitude: 28.3712,
    longitude: -81.5173,
    cuisine_types: ['Frutos do Mar Nobres', 'Carnes Grelhadas (Steakhouse)', 'Ostras Frescas'],
    service_type: 'table_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$$$$',
    reservation_required: false,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: true,
    dietary_options: ['Sem Glúten', 'Vegetariano'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://theboathouseorlando.com/',
    reservation_url: 'https://theboathouseorlando.com/reservations/',
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Restaurante naval sofisticado à beira da lagoa de Disney Springs, com barcos de coleção e os famosos carros anfíbios vintage (Amphicars) que navegam na água.',
    tips: 'Mesmo quando não há reservas no app da Disney, o site OpenTable frequentemente possui mesas disponíveis para o The Boathouse!',
    source_ids: ['src-005'],
  },
  {
    restaurant_id: 'food-032',
    name: "Gideon's Bakehouse",
    normalized_name: 'gideons bakehouse',
    operator: 'independent',
    location_type: 'disney_springs',
    resort: null,
    park: null,
    park_area: 'The Landing',
    shopping_center: 'Disney Springs',
    address: 'Disney Springs The Landing, Lake Buena Vista, FL 32830',
    latitude: 28.3705,
    longitude: -81.5165,
    cuisine_types: ['Cookies Artesanais Gigantes', 'Cafés Gelados Especiais', 'Bolos'],
    service_type: 'kiosk_snack',
    meal_types: ['snack'],
    price_category: '$',
    reservation_required: false,
    reservation_recommended: false,
    mobile_order_available: false,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: false,
    dietary_options: ['Vegetariano'],
    accessibility_information: 'Entrada acessível',
    official_url: 'https://gideonsbakehouse.com/',
    reservation_url: null,
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Famosa por cookies artesanais de quase 250 gramas cada, assados lentamente por 24 horas e repletos de gotas de chocolate. Decoração gótica vitoriana imersiva.',
    tips: 'A fila física costuma passar de 1 a 2 horas. Chegue no início da manhã para entrar na fila virtual presencial com um atendente na porta.',
    source_ids: ['src-005'],
  },
  {
    restaurant_id: 'food-033',
    name: 'Three Broomsticks',
    normalized_name: 'three broomsticks',
    operator: 'universal',
    location_type: 'in_park',
    resort: 'Universal Orlando Resort',
    park: 'islands-of-adventure',
    park_area: 'The Wizarding World of Harry Potter — Hogsmeade',
    shopping_center: null,
    address: 'Universal Islands of Adventure, Orlando, FL 32819',
    latitude: 28.4727,
    longitude: -81.4735,
    cuisine_types: ['Britânica Tradicional', 'Shepherd’s Pie & Ribs', 'Cerveja Amanteigada'],
    service_type: 'quick_service',
    meal_types: ['breakfast', 'lunch', 'dinner'],
    price_category: '$$',
    reservation_required: false,
    reservation_recommended: false,
    mobile_order_available: true,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano', 'Sem Glúten'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://www.universalorlando.com/web/en/us/things-to-do/dining/three-broomsticks',
    reservation_url: null,
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'A taberna Três Vassouras de Hogsmeade, com arquitetura torta de madeira e pratos britânicos autênticos como Fish & Chips, costelinhas defumadas e cerveja amanteigada gelada.',
    tips: 'O Great Feast é uma travessa imensa que alimenta 4 pessoas com frango assado, costela, espigas de milho e batatas por um excelente valor em grupo.',
    source_ids: ['src-007'],
  },
  {
    restaurant_id: 'food-034',
    name: 'Mythos Restaurant',
    normalized_name: 'mythos restaurant',
    operator: 'universal',
    location_type: 'in_park',
    resort: 'Universal Orlando Resort',
    park: 'islands-of-adventure',
    park_area: 'The Lost Continent',
    shopping_center: null,
    address: 'Universal Islands of Adventure, Orlando, FL 32819',
    latitude: 28.4718,
    longitude: -81.4717,
    cuisine_types: ['Mediterrânea & Internacional', 'Frutos do Mar', 'Carnes & Risotos'],
    service_type: 'table_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$$$',
    reservation_required: false,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano', 'Sem Glúten'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://www.universalorlando.com/web/en/us/things-to-do/dining/mythos-restaurant',
    reservation_url: 'https://www.universalorlando.com/web/en/us/things-to-do/dining/mythos-restaurant',
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Premiado repetidas vezes como o melhor restaurante de parque temático do mundo. Construído dentro de uma caverna marinha esculpida com figuras mitológicas gregas e vista para o lago.',
    tips: 'Reserve pelo app oficial da Universal ou presencialmente logo pela manhã na entrada do restaurante.',
    source_ids: ['src-007', 'src-010'],
  },
  {
    restaurant_id: 'food-035',
    name: 'Leaky Cauldron',
    normalized_name: 'leaky cauldron',
    operator: 'universal',
    location_type: 'in_park',
    resort: 'Universal Orlando Resort',
    park: 'universal-studios',
    park_area: 'The Wizarding World of Harry Potter — Diagon Alley',
    shopping_center: null,
    address: 'Universal Studios Florida, Orlando, FL 32819',
    latitude: 28.4792,
    longitude: -81.4695,
    cuisine_types: ['Britânica Tradicional', 'Tortas de Carne', 'Café da Manhã Inglês'],
    service_type: 'quick_service',
    meal_types: ['breakfast', 'lunch', 'dinner'],
    price_category: '$$',
    reservation_required: false,
    reservation_recommended: false,
    mobile_order_available: true,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://www.universalorlando.com/web/en/us/things-to-do/dining/leaky-cauldron',
    reservation_url: null,
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'O pub Caldeirão Furado no Beco Diagonal, com o caldeirão de verdade fervilhando na lareira e pratos clássicos como Cottage Pie, Bangers and Mash e suco de abóbora.',
    tips: 'Chegue um pouco antes do horário de pico do almoço (11h45) para encontrar mesas livres sob os tetos altos góticos.',
    source_ids: ['src-006'],
  },
  {
    restaurant_id: 'food-036',
    name: "Finnegan's Bar & Grill",
    normalized_name: 'finnegans bar and grill',
    operator: 'universal',
    location_type: 'in_park',
    resort: 'Universal Orlando Resort',
    park: 'universal-studios',
    park_area: 'New York',
    shopping_center: null,
    address: 'Universal Studios Florida, Orlando, FL 32819',
    latitude: 28.4781,
    longitude: -81.4708,
    cuisine_types: ['Pub Irlandês Tradicional', 'Fish & Chips', 'Chopes Importados'],
    service_type: 'table_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$$',
    reservation_required: false,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: true,
    dietary_options: ['Vegetariano'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://www.universalorlando.com/web/en/us/things-to-do/dining/finnegans-bar-grill',
    reservation_url: null,
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Pub irlandês autêntico no coração de New York em USF, com música ao vivo típica, balcão de madeira nobre e pratos clássicos como carne enlatada com repolho e torta de pastor.',
    tips: 'Excelente ponto de refúgio climatizado para descansar os pés à tarde com uma cerveja gelada ou almoço completo.',
    source_ids: ['src-006'],
  },
  {
    restaurant_id: 'food-037',
    name: 'Toadstool Cafe',
    normalized_name: 'toadstool cafe',
    operator: 'universal',
    location_type: 'in_park',
    resort: 'Universal Epic Universe',
    park: 'epic-universe',
    park_area: 'Super Nintendo World',
    shopping_center: null,
    address: 'Universal Epic Universe, Orlando, FL 32819',
    latitude: 28.4515,
    longitude: -81.4421,
    cuisine_types: ['Temática Divertida Nintendo', 'Hambúrgueres & Sopas de Cogumelo', 'Sobremesas Lúdicas'],
    service_type: 'quick_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$$',
    reservation_required: false,
    reservation_recommended: true,
    mobile_order_available: true,
    character_dining: false,
    characters: ['Chef Toad (nas telas interativas)'],
    dining_plan_eligibility: false,
    dietary_options: ['Vegetariano', 'Sem Glúten'],
    accessibility_information: 'Totalmente acessível para cadeirantes',
    official_url: 'https://www.universalorlando.com/web/en/us/theme-parks/epic-universe',
    reservation_url: null,
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Restaurante principal de Super Nintendo World dentro de um cogumelo gigante onde o Chef Toad cozinha pratos lúdicos exibidos em janelas panorâmicas do Reino dos Cogumelos.',
    tips: 'Exige agendamento de horário de retorno via QR code logo na entrada da terra pela manhã cedo nos dias de alta visitação.',
    source_ids: ['src-001'],
  },
  {
    restaurant_id: 'food-038',
    name: 'Das Stakehaus',
    normalized_name: 'das stakehaus',
    operator: 'universal',
    location_type: 'in_park',
    resort: 'Universal Epic Universe',
    park: 'epic-universe',
    park_area: 'Dark Universe',
    shopping_center: null,
    address: 'Universal Epic Universe, Orlando, FL 32819',
    latitude: 28.4528,
    longitude: -81.4435,
    cuisine_types: ['Carnes & Espetos Góticos', 'Churrasco Europeu', 'Cervejas Artesanais'],
    service_type: 'quick_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$$',
    reservation_required: false,
    reservation_recommended: false,
    mobile_order_available: true,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: false,
    dietary_options: ['Opção Vegetariana'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://www.universalorlando.com/web/en/us/theme-parks/epic-universe',
    reservation_url: null,
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Restaurante temático gótico dos servos dos vampiros em Dark Universe, construído sobre catacumbas antigas servindo carnes assadas e pratos fortes.',
    tips: 'A ambientação com estacas de madeira e esculturas de morcegos é impressionante e super imersiva.',
    source_ids: ['src-001'],
  },
  {
    restaurant_id: 'food-039',
    name: 'Sharks Underwater Grill',
    normalized_name: 'sharks underwater grill',
    operator: 'seaworld',
    location_type: 'in_park',
    resort: 'SeaWorld Orlando',
    park: 'seaworld',
    park_area: 'Shark Realm',
    shopping_center: null,
    address: '7007 SeaWorld Dr, Orlando, FL 32821',
    latitude: 28.4112,
    longitude: -81.4615,
    cuisine_types: ['Frutos do Mar Nobres', 'Carnes Grelhadas', 'Menu Infantil'],
    service_type: 'table_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$$$',
    reservation_required: false,
    reservation_recommended: true,
    mobile_order_available: false,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: false,
    dietary_options: ['Vegetariano', 'Sem Glúten'],
    accessibility_information: 'Acessível para cadeirantes',
    official_url: 'https://seaworld.com/orlando/dining/sharks-underwater-grill/',
    reservation_url: 'https://seaworld.com/orlando/dining/sharks-underwater-grill/',
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Restaurante requintado com paredes de vidro do chão ao teto voltadas para um aquário panorâmico onde tubarões de várias espécies e arraias nadam tranquilamente ao lado das mesas.',
    tips: 'Excelente fuga do calor do SeaWorld. Se desejar almoçar, faça a reserva presencial assim que o parque abrir diretamente na recepção do restaurante.',
    source_ids: ['src-001'],
  },
  {
    restaurant_id: 'food-040',
    name: "Voyager's Smokehouse",
    normalized_name: 'voyagers smokehouse',
    operator: 'seaworld',
    location_type: 'in_park',
    resort: 'SeaWorld Orlando',
    park: 'seaworld',
    park_area: 'Waterfront',
    shopping_center: null,
    address: '7007 SeaWorld Dr, Orlando, FL 32821',
    latitude: 28.4095,
    longitude: -81.4608,
    cuisine_types: ['Churrasco Americano (BBQ)', 'Costela Defumada', 'Frango e Brisket'],
    service_type: 'quick_service',
    meal_types: ['lunch', 'dinner'],
    price_category: '$$',
    reservation_required: false,
    reservation_recommended: false,
    mobile_order_available: true,
    character_dining: false,
    characters: [],
    dining_plan_eligibility: true,
    dietary_options: ['Opção Vegetariana'],
    accessibility_information: 'Totalmente acessível',
    official_url: 'https://seaworld.com/orlando/dining/voyagers-smokehouse/',
    reservation_url: null,
    operational_status: 'confirmed',
    last_verified_at: '2026-10-08',
    visibility: 'active',
    short_description: 'Churrascaria estilo cafeteria no SeaWorld onde as carnes são defumadas lentamente ao vivo em lenha de nogueira, produzindo um aroma irresistível por todo o parque.',
    tips: 'É elegível para o plano All Day Dining Deal do SeaWorld, o que o torna uma das escolhas mais vantajosas de custo-benefício do dia.',
    source_ids: ['src-001'],
  },
];
''';

with open('src/data/diningCatalog.ts', 'w', encoding='utf-8') as f:
    f.write(catalog_script)

print("Generated src/data/diningCatalog.ts successfully!")
